### ISSUE TITLE
Requires password within the universitys network

### ISSUE THREAD

**Issue by Paktosan** [lutzthies/robolab-docs-issue-tracker#15]
In an dormitory where internet is provided by AG DSN, the Robolab website requires a password anyway. It should be accessible anyway.

**Comment by MartinNowack** [comment]
@Paktosan I need the subnet/mask for this network after that I can decide.

**Comment by Paktosan** [comment]
Hi, I attached a partial dump from the AG DSN wiki which shows which house uses which subnets.
[Netze – AG DSN Wiki.pdf](https://github.com/7HAL32/robolab-docs-issue-tracker/files/1778647/Netze.AG.DSN.Wiki.pdf)

**Comment by MartinNowack** [comment]
@Paktosan Thanks for the information. I added the appropriate subnets. If this is solved for you, please close this bug.

**Comment by lutzthies** [comment]
@Paktosan Any update on this issue?

**Comment by Paktosan** [comment]
Sorry, forgot to write you. Yes, I am able to access the site from my dormitory now.
