### ISSUE TITLE
Broken link for Language Bindings 

### ISSUE THREAD

**Issue by friedrichweise** [lutzthies/robolab-docs-issue-tracker#16]
The GitHub link for installing ev3dev language bindings seems to be broken. The documented repository https://github.com/7HAL32/ev3dev-lang-python ([Docs > Development Environment > Python](http://robolab.inf.tu-dresden.de/dev/python/)) returns a 404.

**Comment by lutzthies** [comment]
Thanks. :)
Fixed.
