### ISSUE TITLE
invalid json

### ISSUE THREAD

**Issue by FelixRTU** [lutzthies/robolab-docs-issue-tracker#21]
Mistake in https://robolab.inf.tu-dresden.de/inf/task/communication/#_nachrichten .The following json code is invalid 

```{"from":"server","type":"planet","payload":{"planetName": "<PLANET_NAME>","startX":"<X>","startY":"<Y>",}}```

to replicate:

```
from json import loads
loads('{"from":"server","type":"planet","payload":{"planetName":"<PLANET_NAME>","startX": "<X>","startY": "<Y>",}}')
```

--> json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 106 (char 105)

fix: remove last comma

**Comment by knobsam** [comment]
Fix comitted and deployed.

**Comment by lutzthies** [comment]
Thanks! Fixed in https://github.com/7HAL32/robolab-docs/commit/e340ed37aad026701be43b7d5059bf4457889a88
