### ISSUE TITLE
Dev Environment/Python/Problems & Help links to wrong Python version

### ISSUE THREAD

**Issue by maxrugen** [lutzthies/robolab-docs-issue-tracker#22]
Version bump from 3.6 (https://docs.python.org/3.6/) to 3.7 (https://docs.python.org/3.7/).

**Comment by lutzthies** [comment]
Thanks! Fixed in https://github.com/7HAL32/robolab-docs/commit/1f3ee0a0f6b440823423da72daf7674d95e732de
