### ISSUE TITLE
target <X>,<Y>

### ISSUE THREAD

**Issue by sambP** [lutzthies/robolab-docs-issue-tracker#3]
Wie soll man mit dem target Befehl umgehen wenn man das angegebene Ziel nicht kennt?
Speichern und anfahren sobald der Weg bekannt ist? 
Was soll passieren wenn man ein neues target bekommt bevor man das alte erreicht hat?

**Comment by lutzthies** [comment]
Danke für die Fragen. Die folgenden Erklärungen werden bald auch ihren Weg in die Dokumentation finden.

> Wie soll man mit dem target Befehl umgehen wenn man das angegebene Ziel nicht kennt?
Speichern und anfahren sobald der Weg bekannt ist?

Das Ziel muss in irgendeiner Form zwischengespeichert werden. Die Erkundung kann dann ohne Veränderung in der Suchstrategie fortgesetzt werden bis das Ziel erreicht wurde. Es muss keine Heuristik zum möglichst optimalen Anfahren verwendet werden. Allerdings können am Ende des Praktikums besonders "schöne" Lösungen von den Betreuern durch Bonuspunkte belohnt werden. 

> Was soll passieren wenn man ein neues target bekommt bevor man das alte erreicht hat?

In diesem Fall wird das bestehende Ziel ersetzt. Sollte ein Pfad zum neuen Ziel bekannt sein, wird die Erkundung abgebrochen und auf kürzestem Weg zum Ziel gefahren. Andernfalls gelten die Bemerkungen aus dem vorherigen Absatz.

**Comment by lutzthies** [comment]
Der [entsprechende Abschnitt in der Doku](http://robolab.inf.tu-dresden.de/inf/task/mqtt/#_planetennachrichten_und_die_kommunikation_mit_dem_mutterschiff) wurde aktualisiert und ist nun präziser formuliert.
