### ISSUE TITLE
Exam: git reset commands

### ISSUE THREAD

**Issue by krabo0om** [lutzthies/robolab-docs-issue-tracker#7]
Add the commands which will be executed by us before the exam so they can test them themselves.

**Comment by krabo0om** [comment]
add a warning that those commands will delete local changes.
maybe they should just clone it into a temporary location and checkout the files? that should give the same results.

**Comment by lutzthies** [comment]
> maybe they should just clone it into a temporary location and checkout the files? that should give the same results.

Good point. We will evaluate this during the next team meeting.

**Comment by lutzthies** [comment]
Done.
Added note on that as well as other important stuff to `Prüfung`.
