### ISSUE TITLE
Add timing constraints

### ISSUE THREAD

**Issue by krabo0om** [lutzthies/robolab-docs-issue-tracker#8]
Enhance the exam part with a time limit, 15 minutes for the large planet, 7 minutes for the small one.

**Comment by krabo0om** [comment]
Die Prüfung besteht wie in den vergangenen Jahren aus zwei Teilen. Auf einem kleinen Planeten werden die Grundfunktionen des Roboters getestet, wie die Kantenverfolgung, die Odometrie oder die Kommunikation. **Um diesen vollständig zu erkunden hat der Roboter 7 Minuten Zeit.** Wurde dies erfolgreich absolviert, bietet anschließend ein großer Planet die Möglichkeit, zusätzlich die Hinderniserkennung und die Berechnung des kürzesten Weges zu prüfen. Nur wenn der Roboter auf dem großen Planeten besteht **und es in unter 15 Minuten abschließt**, kann die Höchstnote erreicht werden.
**Beide Zeitangaben sind hierbei als Richtwerte zu sehen um extrem langsame Roboter zu vermeiden, die bei Überschreitung die Bestnote nicht mehr erreichen können. Trotzdem sollten Geschwindigkeitsoptimierungen erst nach dem erfolgreichen Implementieren aller anderen Aufgabenteile vorgenommen werden.**

**Comment by lutzthies** [comment]
Done.
